### ISSUE TITLE
Not sure whether this is a config error

### ISSUE THREAD

**Issue by cxxszz** [elias-ramzi/HAPPIER#2]
Dear authors,

When I tried to run the code, I had an error and the full traceback is as follows.

`
Traceback (most recent call last):
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
    overrides=args.overrides,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 105, in run
    configure_logging=with_log_configuration,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/core/utils.py", line 122, in run_job
    working_dir = str(OmegaConf.select(config, job_dir_key))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 691, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/_utils.py", line 818, in format_and_raise
    _raise(ex, cause)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 688, in select
    throw_on_missing=throw_on_missing,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/_impl.py", line 63, in select_value
    absolute_key=absolute_key,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/_impl.py", line 96, in select_node
    throw_on_resolution_failure=throw_on_resolution_failure,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 434, in _select_impl
    memo=memo,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 622, in _maybe_resolve_interpolation
    memo=memo if memo is not None else set(),
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 483, in _resolve_interpolation_from_parse_tree
    parse_tree=parse_tree, node=value, key=key, parent=parent, memo=memo
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 911, in accept
    return visitor.visitInterpolationNode(self)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 643, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 570, in _resolve_node_interpolation
    ).with_traceback(sys.exc_info()[2])
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 565, in _resolve_node_interpolation
    memo=memo,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/base.py", line 416, in _select_impl
    throw_on_type_error=throw_on_resolution_failure,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 1088, in _select_one
    f"Missing mandatory value: {c._get_full_key(ret_key)}"
omegaconf.errors.InterpolationToMissingValueError: MissingMandatoryValue while resolving interpolation: Missing mandatory value: experience.experiment_name
    full_key: hydra.run.dir
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    run()
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/home/lwj/miniconda3/envs/happier/lib/python3.7/site-packages/hydra/_internal/utils.py", line 270, in run_and_report
    cur.tb_lasti = iter_tb.tb_lasti
AttributeError: 'NoneType' object has no attribute 'tb_lasti'
`

According to [https://github.com/facebookresearch/hydra/issues/1382](url), this seems to be an error caused by the config but I'm not very sure. Could you please give some advice on how to fix this error？

**Comment by elias-ramzi** [comment]
Hi!

I think this is because you did not enter an experiment_name (`Missing mandatory value: experience.experiment_name`). In the code this value is mandatory in order to create a unique folder for each run.

e.g. on SOP in the README:
```
'experience.experiment_name=HAPPIER_SOP' \
```

Hope this helps!

**Comment by cxxszz** [comment]
Thank you for your kind and prompt reply! 

Running `CUDA_VISIBLE_DEVICES='0' python happier/run.py \                             
'experience.experiment_name=HAPPIER_SOP' \
'experience.log_dir=experiments/HAPPIER' \
experience.seed=0 \
experience.max_iter=100 \
experience.warmup_step=5 \
experience.accuracy_calculator.compute_for_hierarchy_levels='[0,1]' \
optimizer=sop \
model=resnet_ln \
transform=sop \
dataset=sop \
loss=HAPPIER_SOP +dataset.data_dir='data/Stanford_Online_Products'` does not lead to errors.

However, the program seems not running. It only produces a folder `HAPPIER/experiments/HAPPIER/HAPPIER_SOP/outputs/experiments/HAPPIER/HAPPIER_SOP/logs`. Is this expected?

I tried to read the event file in this folder. It contains the following contents
```
wall_time: 1676543740.7528827
file_version: "brain.Event:2"

wall_time: 1676543740.7532778
file_version: "brain.Event:2"

wall_time: 1676543740.75331
session_log {
  status: START
}
```

And the `run.log` file is as follows:
```
[2023-02-16 18:35:40,753][HAPPIER][INFO] - Training with seed 0
[2023-02-16 18:35:40,758][HAPPIER][INFO] - Compose(
    Resize(size=256, interpolation=bilinear)
    RandomResizedCrop(size=(224, 224), scale=(0.16, 1), ratio=(0.75, 1.33), interpolation=bilinear)
    RandomHorizontalFlip(p=0.5)
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)
[2023-02-16 18:35:40,758][HAPPIER][INFO] - Compose(
    Resize(size=[256, 256], interpolation=bilinear)
    CenterCrop(size=(224, 224))
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)
[2023-02-16 18:38:28,384][HAPPIER][WARNING] - Exiting trial, experiment HAPPIER_SOP already exists
[2023-02-16 18:38:28,384][HAPPIER][WARNING] - Its access: experiments/HAPPIER/HAPPIER_SOP
[2023-02-16 18:59:45,767][HAPPIER][WARNING] - Exiting trial, experiment HAPPIER_SOP already exists
[2023-02-16 18:59:45,767][HAPPIER][WARNING] - Its access: experiments/HAPPIER/HAPPIER_SOP

```

Do I need to further run `happier/evaluate.py` to get the image retrieval result?

**Comment by elias-ramzi** [comment]
I think you ran the experiment while the folder already existed (`Exiting trial, experiment HAPPIER_SOP already exists`).

Try removing the folder: `rm -r experiments/HAPPIER/HAPPIER_SOP`. And then rerun the experiment.
The training should happen and the model will be evaluated each 20 epochs.

**Comment by cxxszz** [comment]
Thank you so much! This solves my problem.

**Comment by elias-ramzi** [comment]
Glad I could help!
